index:
    path:     /
    defaults: { controller: 'MainController', action: 'loginAction' }

# MianController
login:
    path:     /login
    defaults : {controller: 'MainController', action: 'loginAction'}
main:
    path:     /main
    defaults: { controller: 'MainController', action: 'indexAction' }

# MenuController
menu:
    path:     /menu
    defaults: { controller: 'MainController', action: 'menuAction' }
menuList:
    path:     /menuList
    defaults: { controller: 'MenuController', action: 'menuListAction' }
getMenuList:
    path:     /getMenuList
    defaults: { controller: 'MenuController', action: 'getMenuListAction' }
doSaveItem:
    path:     /doSaveItem
    defaults: { controller: 'MenuController', action: 'doSaveItemAction' }
getParentItem:
    path:     /getParentItem
    defaults: { controller: 'MenuController', action: 'getParentItemAction' }
deleteItem:
    path:     /deleteItem
    defaults: { controller: 'MenuController', action: 'deleteItemAction' }

# permController
listUserPerm:
    path:     /listPerm
    defaults: { controller: 'PermController', action: 'listPermAction' }
getUserPerm:
    path:     /getUserPerm
    defaults: { controller: 'PermController', action: 'getUserPermAction' }
getMenuCheckTree:
    path:     /getMenuCheckTree
    defaults: { controller: 'PermController', action: 'getMenuCheckTreeAction' }

#UserController
doSaveUser:
    path:     /doSaveUser
    defaults: { controller: 'UserController', action: 'doSaveUserAction' }


#util:
getValidCode:
    path:     /getValidCode
    defaults: { controller:  'UtilController', action: 'getValidCodeAction' }
#imports:
#    - { resource: main-routing.yml }
#    - { resource: menu-routing.yml }



