login:
    path:     /login
    defaults : {controller: 'MainController', action: 'loginAction'}
main:
    path:     /main
    defaults: { controller: 'MainController', action: 'indexAction' }
index:
    path:     /
    defaults: { controller: 'MainController', action: 'indexAction' }